View/Controllers/CategoriaController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Repository.Repositories;

namespace View.Controllers
{
    public class CategoriaController : Controller
    {
        private CategoriaRepository repositorio;

        public CategoriaController()
        {
            repositorio = new CategoriaRepository();
        }
        // GET: Categoria
        public ActionResult Index()
        {
            List<Categoria> categorias = repositorio.ObterTodos();
            ViewBag.Categorias = categorias;
            return View();
        }

        public ActionResult Cadastro()
        {
            
            return View();

        }

        public ActionResult Store(string nome)
        {
            Categoria categoria = new Categoria();
            categoria.Nome = nome;
            repositorio.Inserir(categoria);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Categoria categoria = repositorio.ObterPeloId(id);
            ViewBag.Categoria = categoria;          
            
            return View();
        }

        public ActionResult Update(int id, string nome)
        {
            Categoria categoria = new Categoria();
            categoria.Id = id;
            categoria.Nome = nome;
            repositorio.Alterar(categoria);

            return RedirectToAction("Index");
        }

    }
}

View/Controllers/ClienteController.cs
using Model;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class ClienteController : Controller
    {

        private ClienteRepository clienteRepository;
        private ContabilidadeRepository contabilidadeRepository;

        public ClienteController()
        {
            clienteRepository = new ClienteRepository();
            contabilidadeRepository = new ContabilidadeRepository();
        }

        // GET: Cliente
        public ActionResult Index()
        {
            List<Cliente> clientes = clienteRepository.ObterTodos();

            ViewBag.Clientes = clientes;
            return View();
        }

        public ActionResult Cadastro()
        {
            List<Contabilidade> contabilidades = contabilidadeRepository.ObterTodos();
            ViewBag.Contabilidades = contabilidades;
            return View();
        }

        public ActionResult Store(int IdContabilidade, string nome, string cpf)
        {
            Cliente cliente = new Cliente();

            cliente.IdContabilidade = IdContabilidade;
            cliente.Cpf = cpf;
            cliente.Nome = nome;

            clienteRepository.Inserir(cliente);

            return RedirectToAction("Index");

        }

        public ActionResult Editar(int id)
        {
            Cliente cliente = clienteRepository.ObterPeloId(id);
            ViewBag.Cliente = cliente;

            List<Contabilidade> contabilidades = contabilidadeRepository.ObterTodos();
            ViewBag.Contabilidades = contabilidades;

            return View();
        }


        public ActionResult Update(int id, int IdContabilidade, string nome, string cpf)
        {
            Cliente cliente = new Cliente();
            cliente.Id = id;
            cliente.Nome = nome;
            cliente.IdContabilidade = IdContabilidade;
            cliente.Cpf = cpf;

            clienteRepository.Alterar(cliente);


            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            clienteRepository.Apagar(id);

            return RedirectToAction("Index");
        }
    }
}

View/Controllers/CompraController.cs
using Model;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class CompraController : Controller
    {
        private CompraRepository repository;
        private CartaoCreditoRepository cartaoRepository;
        public CompraController()
        {
            repository = new CompraRepository();
            cartaoRepository = new CartaoCreditoRepository();
        }

        // GET: Compra
        public ActionResult Index()
        {
            List<Compra> compras = repository.ObterTodos();
            ViewBag.Compras = compras;
            return View();
        }

        public ActionResult Cadastro()
        {
            List<CartaoCredito> cartoesCredito = cartaoRepository.ObterTodos();
            ViewBag.Cartoes = cartoesCredito;            
            

            return View();

        }

        public ActionResult Store(int idCartaoCredito, decimal valor, DateTime dataCompra)
        {
            Compra compra = new Compra();
            compra.IdCartao = idCartaoCredito;
            compra.Valor = valor;
            compra.DataCompra = dataCompra;

            repository.Inserir(compra);

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Compra compra = repository.ObterPeloId(id);

            ViewBag.Compra = compra;

            return View();
        }

        public ActionResult Update (int id, int idCartaoCredito, decimal valor, DateTime dataCompra)
        {
            Compra compra = new Compra();

            compra.Id = id;
            compra.IdCartao = idCartaoCredito;
            compra.Valor = valor;
            compra.DataCompra = dataCompra;

            repository.Alterar(compra);

            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);

            return RedirectToAction("Index");

        }
    }
}

View/Controllers/UsuarioController.cs
using Model;
using Repository.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace View.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioRepository repository;
        private ContabilidadeRepository contabilidadeRepostory;

        public UsuarioController()
        {
            repository = new UsuarioRepository();
            contabilidadeRepostory = new ContabilidadeRepository();
        }

        // GET: Usuario
        public ActionResult Index()
        {
            List<Usuario> usuarios = repository.ObterTodos();
            ViewBag.Usuarios = usuarios;
            return View();
        }

        public ActionResult Cadastro()
        {
            List<Contabilidade> contabilidades = contabilidadeRepostory.ObterTodos();
            ViewBag.Contabilidades = contabilidades;
            return View();
        }

        public ActionResult Store(int idContabilidade, string login, string senha, DateTime dataNascimento)
        {
            Usuario usuario = new Usuario();

            usuario.IdContabilidade = idContabilidade;
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.DataNascimento = dataNascimento;

            repository.Inserir(usuario);

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Usuario usuario = repository.ObterPeloId(id);

            ViewBag.Usuario = usuario;

            List<Contabilidade> contabilidades = contabilidadeRepostory.ObterTodos();
            ViewBag.Contabilidades = contabilidades;

            return View();
        }

        public ActionResult Update(int id, int idContabilidade, string login, string senha, DateTime dataNascimento)
        {
            Usuario usuario = new Usuario();

            usuario.IdContabilidade = idContabilidade;
            usuario.Id = id;
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.DataNascimento = dataNascimento;

            repository.Alterar(usuario);
            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            repository.Apagar(id);

            return View();
        }
    }
}

View/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="icon" href="~Content/flogo.ico" />
</head>
<body>
    <nav class="navbar navbar-expand navbar-light bg-info text-monospace">

        <a class="navbar-brand font-weight-bold" href="#">CONTABIL</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarNav">
            <ul class="nav navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "Categoria")">Categorias</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "Contabilidade")">Contabilidades</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "Compra")">Compras</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "Cliente")">Clientes</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "Usuario")">Usuários</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "CartaoCredito")">Cartão de Crédito</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "ContaPagar")">Contas a Pagar</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index" , "ContaReceber")">Contas a Receber</a>
                </li>





            </ul>
        </div>




    </nav>


    <div class="container body-content">
        @RenderBody()

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>